loongarch/tlb: fix "error: parameter 'ptep' set but not used" due to __tlb_remove_tlb_entry()
With LLVM=1 and W=1 we get:

./include/asm-generic/tlb.h:629:10: error: parameter 'ptep' set
but not used [-Werror,-Wunused-but-set-parameter]
      629 |                 pte_t *ptep, unsigned int nr, unsigned long address)
          |                        ^

We fixed a similar issue via Arnd in the original commit, but forgot
about the loongarch variant. Turns out, there is no need for loongarch
to have a custom variant, so let's just drop it and rely on the asm-generic
variant

Reported-by: Miguel Ojeda <miguel.ojeda.sandonis@gmail.com>
Closes: https://lkml.kernel.org/r/CANiq72mQh3O9S4umbvrKBgMMorty48UMwS01U22FR0mRyd3cyQ@mail.gmail.com
Fixes: 4d5bf0b6183f ("mm/mmu_gather: add tlb_remove_tlb_entries()")
Tested-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David Hildenbrand <david@redhat.com>